In [2]:
data = [(2010, 2), (2009, 4), (1989, 8), (2009, 7)]

In [3]:
type(data)

list

In [7]:
import numpy as np
data = np.array(data)

In [13]:
data

array([[2010,    2],
       [2009,    4],
       [1989,    8],
       [2009,    7]])

In [14]:
type(data)

numpy.ndarray

In [10]:
years_dict = dict()

In [11]:
for line in data:
    if line[0] in years_dict:
        # append the new number to the existing array at this slot
        years_dict[line[0]].append(line[1])
    else:
        # create a new array in this slot
        years_dict[line[0]] = [line[1]]

In [12]:
years_dict

{1989: [8], 2009: [4, 7], 2010: [2]}

In [32]:
possible_states = {0,1,2}
temp = np.array([0.9, 0.8, 0.1, 0])

In [33]:
temp[[x for x in possible_states]]

array([0.9, 0.8, 0.1])

In [47]:
a=np.array([1, 2, 3, 4])

print(a, type(a))
np.shape(a)

[1 2 3 4] <class 'numpy.ndarray'>


(4,)

In [51]:
range((np.shape(a))[0])

range(0, 4)